[package]
name = "rosu-pp"
version = "0.9.0"
description = "osu! difficulty and pp calculation for all modes"
authors = ["Max Ohn"]
license = "MIT"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
neon = { version = "0.10", default-features = false, features = ["napi-6"] }
neon-serde3 = { version = "0.10"}
rosu-pp = { version = "0.9" }
serde = { version = "1.0", default-features = false, features = ["derive"] }

